server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/signIn, /api/v1/auth/signUp, /api/v1/users/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - AuthGatewayFilter
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthGatewayFilter
        - id: group-service
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/api/v1/groups/**
          filters:
            - AuthGatewayFilter
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/v1/events/**
          filters:
            - AuthGatewayFilter
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
