server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/clients/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
